import io
from datetime import timezone

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from app.models.account import VirtualAccount
from app.models.tenant import Tenant
from app.models.transaction import Transaction


def generate_receipt(
    tenant: Tenant,
    account: VirtualAccount,
    transaction: Transaction,
) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=2 * cm, bottomMargin=2 * cm)
    styles = getSampleStyleSheet()
    elements = []

    # header
    elements.append(Paragraph(tenant.business_name, styles["Title"]))
    elements.append(Paragraph("Payment Receipt", styles["Heading2"]))
    elements.append(Spacer(1, 0.5 * cm))

    paid_at = transaction.paid_at
    if paid_at and paid_at.tzinfo is None:
        paid_at = paid_at.replace(tzinfo=timezone.utc)

    rows = [
        ["Receipt #", str(transaction.id)[:8].upper()],
        ["Transaction Ref", transaction.nomba_transaction_ref],
        ["Date", paid_at.strftime("%d %B %Y, %H:%M UTC") if paid_at else "—"],
        ["", ""],
        ["Paid By", account.customer_name],
        ["Account Number", account.bank_account_number or "—"],
        ["Bank", account.bank_name or "—"],
        ["", ""],
        ["Amount Paid", f"₦{float(transaction.amount):,.2f}"],
        ["Status", transaction.status.value.upper()],
    ]

    if transaction.expected_amount:
        rows.append(["Amount Expected", f"₦{float(transaction.expected_amount):,.2f}"])
    if transaction.difference and float(transaction.difference) != 0:
        label = "Overpaid By" if float(transaction.difference) > 0 else "Shortfall"
        rows.append([label, f"₦{abs(float(transaction.difference)):,.2f}"])
    if account.description:
        rows.append(["Description", account.description])
    if transaction.narration:
        rows.append(["Narration", transaction.narration])

    table = Table(rows, colWidths=[5 * cm, 11 * cm])
    table.setStyle(
        TableStyle(
            [
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 10),
                ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.whitesmoke, colors.white]),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    elements.append(table)
    elements.append(Spacer(1, 1 * cm))
    elements.append(
        Paragraph(
            "This receipt was generated by Settle. It serves as proof of payment.",
            styles["Italic"],
        )
    )

    doc.build(elements)
    return buffer.getvalue()
