"""add_payment_status_to_virtual_accounts

Revision ID: d72e90d15a27
Revises: 8e59e7a6f109
Create Date: 2026-07-07 23:30:45.642047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd72e90d15a27'
down_revision: Union[str, Sequence[str], None] = '8e59e7a6f109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_accounts', sa.Column('payment_status', sa.String(length=20), server_default='unpaid', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('virtual_accounts', 'payment_status')
    # ### end Alembic commands ###
